timeout: 60sec
central:
  reports:
    datastores:
      - artifact://masakatsube/python_cicd
      - artifact://masakatsube/react_cicd
  badges:
    datastores:
      - local://badges
  push:
    enable: true
